/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as ImprintImport } from './routes/imprint'
import { Route as ExperienceImport } from './routes/Experience'
import { Route as EducationImport } from './routes/Education'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const ImprintRoute = ImprintImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRoute,
} as any)

const ExperienceRoute = ExperienceImport.update({
  id: '/Experience',
  path: '/Experience',
  getParentRoute: () => rootRoute,
} as any)

const EducationRoute = EducationImport.update({
  id: '/Education',
  path: '/Education',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Education': {
      id: '/Education'
      path: '/Education'
      fullPath: '/Education'
      preLoaderRoute: typeof EducationImport
      parentRoute: typeof rootRoute
    }
    '/Experience': {
      id: '/Experience'
      path: '/Experience'
      fullPath: '/Experience'
      preLoaderRoute: typeof ExperienceImport
      parentRoute: typeof rootRoute
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Education': typeof EducationRoute
  '/Experience': typeof ExperienceRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Education': typeof EducationRoute
  '/Experience': typeof ExperienceRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Education': typeof EducationRoute
  '/Experience': typeof ExperienceRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Education' | '/Experience' | '/imprint' | '/privacy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Education' | '/Experience' | '/imprint' | '/privacy'
  id: '__root__' | '/' | '/Education' | '/Experience' | '/imprint' | '/privacy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Education",
        "/Experience",
        "/imprint",
        "/privacy"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Education": {
      "filePath": "Education.tsx"
    },
    "/Experience": {
      "filePath": "Experience.tsx"
    },
    "/imprint": {
      "filePath": "imprint.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
